version: '3.9'

x-env-files: &default-envs
  - ./.envs/.local/.django
  - ./.envs/.local/.postgres

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: mastermind_py_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file: *default-envs
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: mastermind_py_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    expose:
      - "5432"
    env_file:
      - ./.envs/.local/.postgres


volumes:
  local_postgres_data:
  local_postgres_data_backups:
